config/routes.rb
require 'sidekiq/web'
TestMyPointSystem::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Private::API => '/api/private'
  mount Sidekiq::Web => '/sidekiq'

  namespace :family do
    resources :teens do
      resources :incident_reports do
        get 'history', :on => :collection
        member do
          get "review_self_correct"
          get "review_appeal"
        end
      end
      resources :guidelines
      resources :daily_privileges do
        collection do
          post 'sort' => "daily_privileges#sort"
        end
      end
      member do
        get 'settings' => "teens#settings"
      end
    end
    resources :subscription_plans
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :families, controllers: { confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :teen do
    resources :incident_reports do
      member do
        get 'self_correct'
        get 'appeal'
      end
    end
    resources :guidelines
    resources :daily_privileges
  end

  resources :users
  get '/account_settings' => "users#account_settings"
  get '/controll_panel' => 'users#controll_panel'
  get '/welcome' => 'users#tiles'

  root :to => 'home_page#index'

  ActiveAdmin.routes(self)
  get "/*slug" => "pages#show"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Grape::Entity::DSL
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable


  entity :id, :email, :time_zone, :phone, :father_name, :mother_name, :confirmation_token
  attr_accessible :email, :password, :password_confirmation, :remember_me, :phone, :key, :time_zone, :provider, :uid, :user_id, :confirmation_token

  validates :password, :presence => true, :on => :create
  validates :email, :email => true, :if => :email_required?
  validates_confirmation_of :password_confirmation, :on => :create

  def email_required?
    super && provider.blank?
  end

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body

  def can_use_system?
    true
  end

  def time
    Time.now.in_time_zone(time_zone)
  end

  def welcome
    ""
  end

  def coach?
    self.is_a?(Coach)
  end

  def family?
    self.is_a?(Family)
  end

  def teen?
    self.is_a?(Teen)
  end

  def self.image_style
    { :medium => "300x300>", :thumb => "100x100>", :index => "30x30#", :welcome => "118x134#" }
  end

  def deactivate!
    self.generate_confirmation_token!
    self.update_attribute(:confirmed_at, nil)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @family = Family.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @family.persisted?
      sign_in_and_redirect @family, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @family = Family.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @family.persisted?
      sign_in_and_redirect @family, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def controll_panel

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_user
  before_filter :check_possibility_to_use_system, :except => [:account_settings, :update]

  def controll_panel
  end

  def tiles
  end

  def update
    current_user.update_attributes(params[:family])
    redirect_to welcome_path
  end

end

app/views/users/account_settings.html.haml
%h2 Account Settings
= form_for( current_user, :url => user_path(current_user), :validate => true, :method => :put) do |f|
  .input-control.text.span4
    = f.text_field :father_name, :autofocus => true, :class => 'with-helper', :placeholder => 'Father name', :validate => {presence: true}
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.text.span4
    = f.text_field :mother_name, :class => 'with-helper', :placeholder => 'Mother name', :validate => {presence: true}
    %button.helper{:type => 'button', :tabindex => "-1"}
  -#- if current_user.provider.blank?
    -#.input-control.text.span4
      -#= f.email_field :email, :class => 'with-helper', :placeholder => "Email", :validate => {:email => true, :uniqueness => true}
      -#%button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.text.span4
    = f.phone_field :phone, :class => 'with-helper', :placeholder => 'Phone', :type => 'phone', :validate => {presence: true}
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.select.span4
    = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :validate => {presence: true}
  .input-control.text.span4
    = f.text_field :key, :class => 'with-helper', :placeholder => 'Key'
    %button.helper{:type => 'button', :tabindex => "-1"}
  %div= f.submit "Update"
%br
:javascript
  $(document).ready(function(){
    $('#family_time_zone').set_timezone();
  });

app/views/users/controll_panel.html.haml
%h2 Control Panel
%br
.tile.bg-color-blueDark
  = link_to account_settings_path do
    .tile.bg-color-blue.icon
      .tile-content
        %i.icon-cog
      .brand
        .name Account settings
.tile.bg-color-blueDark
  = link_to family_teens_path do
    .tile.bg-color-red.icon
      .tile-content
        %i.icon-user
      .brand
        .name Teens
.tile.bg-color-blueDark
  = link_to family_subscription_plans_path do
    .tile.bg-color-green.icon
      .tile-content
        %i.icon-credit-card
      .brand
        .name Plans

app/views/users/tiles.html.haml
= render "users/tiles/#{current_user.class.to_s.downcase}"