config/routes.rb
require 'sidekiq/web'
TestMyPointSystem::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Private::API => '/api/private'
  mount Sidekiq::Web => '/sidekiq'

  namespace :family do
    resources :teens do
      resources :incident_reports do
        get 'history', :on => :collection
        member do
          get "review_self_correct"
          get "review_appeal"
        end
      end
      resources :guidelines
      resources :daily_privileges do
        collection do
          post 'sort' => "daily_privileges#sort"
        end
      end
      member do
        get 'settings' => "teens#settings"
      end
    end
    resources :subscription_plans
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :families, controllers: { confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :teen do
    resources :incident_reports do
      member do
        get 'self_correct'
        get 'appeal'
      end
    end
    resources :guidelines
    resources :daily_privileges
  end

  resources :users
  get '/account_settings' => "users#account_settings"
  get '/controll_panel' => 'users#controll_panel'
  get '/welcome' => 'users#tiles'

  root :to => 'home_page#index'

  ActiveAdmin.routes(self)
  get "/*slug" => "pages#show"

end

app/views/shared/_admin_video.html.haml
- if video
  %video{:src => video.data.url, :width => 900, :controls => true}

app/views/shared/_auth_form.html.haml
.auth-form
  = form_for(User.new, :as => :user, :url => session_path(:user), :html => {:class => 'auth-form__in'}) do |f|
    %h2 Sign with
    .clearfix
      %a.fl_l{:href => omniauth_authorize_path(:family, :facebook)}
        = image_tag 'images/auth-fb.png', :alt => ''
      %a.fl_r{:href => omniauth_authorize_path(:family, :twitter)}
        = image_tag 'images/auth-twit.png', :alt => ''
    %span.auth-form__div
      %span or
    = f.text_field :email, :size => ''
    .pr
      = f.password_field :password, :size => ''
      = link_to "forgot?", new_password_path(:user), :class => 'auth-form__forgot'
    %input{:type => "submit", :value => "Sign in"}
.overlay
-#
  %h2 Sign in
  = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
    %div
      = f.label :email
      %br/
      = f.email_field :email, :autofocus => true
    %div
      = f.label :password
      %br/
      = f.password_field :password
    - if devise_mapping.rememberable?
      %div
        = f.check_box :remember_me
        = f.label :remember_me
    %div= f.submit "Sign in"
  = render "devise/shared/links"

app/views/shared/_header.html.haml
- demo_video = Video.where(:description => "Demo Video").first
= render :partial => 'shared/auth_form'
%header.header{:role => "banner"}
  .header__top.center
    .wrapper
      - if demo_video
        .fl_l
          %a.link-video{:href => "#"} Demo — how it works
      .fl_r
        %ul.nav_auth
          - if current_user
            %li
              = link_to "Welcome #{current_user.welcome}", welcome_path
              %i /
            %li
              = link_to "#{t(:logout)}", destroy_user_session_path, :method => :delete
          - else
            %li.nav_auth__login_blue
              %a#auth-form{:href => "#login"} Login
              %i /
            %li
              =link_to t(:sign_up), new_family_registration_path
      -#.fl_r
        -#%a{:href => "#"}
          -#Download MyPointSystem for
          -#%strong.iphone-dload iPhone
  .header__bottom
    .wrapper
      %a.logo{:href => root_path}
      = render :partial => 'shared/nav_bar'
:javascript
  $(document).ready(function(){
      $('a.link-video').click(function(e) {
          $.Dialog({
              'title'      : 'Add Teen',
              'content'    : "#{j render(:partial => 'shared/admin_video',
                                         :locals => {:video => demo_video})}",
              'closeButton' : true,
              'position'   : {
                'offsetY'    : 50
              },
          });
      });
  });

app/views/shared/_nav_bar.html.haml
%nav
  %ul.nav_main
    %li
      %a{:href => '/'} Home
    - Page.visible.each do |page|
      %li
        %a{:href => page.slug}= page.title

app/views/shared/_slider.html.haml
.carousel{"data-param-direction" => "left", "data-param-duration" => "2000", "data-param-effect" => "slide", "data-param-period" => "4000", "data-role" => "carousel"}
  .slides
    #slide1.slide.mixed
      = image_tag 'images/slide.jpg'
      .description.red
        %h2 The best way to motivate children to learn
        %p
          A flexible system of rewards
          promotes personal growth
          of the teen
        %a.learn-more{:href => "#"}
          %i.icon-arrow-right-3
          learn more
          %br about us
    #slide2.slide.mixed
      = image_tag 'images/slide.jpg'
      .description.green
        %h2 The best way to motivate children to learn
        %p
          A flexible system of rewards
          promotes personal growth
          of the teen
        %a.learn-more{:href => "#"}
          %i.icon-arrow-right-3
          learn more
          %br about us
    #slide3.slide.mixed
      = image_tag 'images/slide.jpg'
      .description.yellow
        %h2 The best way to motivate children to learn
        %p
          A flexible system of rewards
          promotes personal growth
          of the teen
        %a.learn-more{:href => "#"}
          %i.icon-arrow-right-3
          learn more
          %br about us