config/routes.rb
require 'sidekiq/web'
TestMyPointSystem::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Private::API => '/api/private'
  mount Sidekiq::Web => '/sidekiq'

  namespace :family do
    resources :teens do
      resources :incident_reports do
        get 'history', :on => :collection
        member do
          get "review_self_correct"
          get "review_appeal"
        end
      end
      resources :guidelines
      resources :daily_privileges do
        collection do
          post 'sort' => "daily_privileges#sort"
        end
      end
      member do
        get 'settings' => "teens#settings"
      end
    end
    resources :subscription_plans
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :families, controllers: { confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :teen do
    resources :incident_reports do
      member do
        get 'self_correct'
        get 'appeal'
      end
    end
    resources :guidelines
    resources :daily_privileges
  end

  resources :users
  get '/account_settings' => "users#account_settings"
  get '/controll_panel' => 'users#controll_panel'
  get '/welcome' => 'users#tiles'

  root :to => 'home_page#index'

  ActiveAdmin.routes(self)
  get "/*slug" => "pages#show"

end

app/models/family.rb
class Family < User
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  attr_accessible :father_name, :mother_name, :coach_id, :from_api
  attr_accessor :from_api
  has_many :guidelines, dependent: :destroy
  has_many :teens, dependent: :destroy
  has_many :daily_privileges, dependent: :destroy
  has_many :incident_reports, dependent: :destroy

  validates :father_name, :presence => true, :unless => :from_api
  validates :mother_name, :presence => true, :unless => :from_api
  validates :phone, :presence => true, :unless => :from_api
  validates :time_zone, :presence => true, :unless => :from_api

  def email_required?
    super && provider.blank?
  end

  def can_use_system?
    self.father_name.present? &&
    self.mother_name.present? &&
    self.phone.present? &&
    self.time_zone.present?
  end

  def available_guidelines
    (self.guidelines + Guideline.default).sort{|v1,v2| v1.id <=> v2.id}.uniq
  end

  def available_daily_privileges
    (self.daily_privileges << DailyPrivilege.default).order(:position)
  end

  def welcome
    if self.father_name.blank? || self.mother_name.blank?
      "#{self.father_name}#{self.mother_name}"
    else
      "#{self.father_name}-#{self.mother_name}"
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = self.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = self.new(father_name:auth.extra.raw_info.name,
                      provider:auth.provider,
                      uid:auth.uid,
                      password:Devise.friendly_token[0,20],
                      from_api: true
                      )
      user.skip_confirmation!
      user.save!
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = self.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = self.new(father_name: auth.extra.raw_info.name,
                      provider:auth.provider,
                      uid:auth.uid,
                      password:Devise.friendly_token[0,20],
                      from_api: true
                      )
      user.skip_confirmation!
      user.save!
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/teen.rb
class Teen < User
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  attr_accessible :date_of_birth, :name, :avatar, :family_id, :time_zone, :points

  validates :name, :presence => true
  validates :phone, :presence => true
  validates :date_of_birth, :format => {:with => /^(0[1-9]|1[0-2])\/([0-2]\d|3[0-1])\/\d{4}$/,
                                        :message => "Format is wrong. Correct format is MM/DD/YYYY"}

  default_scope order(:created_at)

  belongs_to :family

  has_many :guidelines
  has_many :daily_privileges
  has_many :incident_reports

  has_one :image, as: :file_carrier,
                  dependent: :destroy

  after_create :copy_default_guidelines
  after_create :copy_default_daily_privileges

  before_create :set_up_time_zone

  alias_attribute :avatar, :image

  def avatar=(attr)
    avatar_image = self.create_image
    avatar_image.update_attributes!(data: attr) rescue avatar_image.destroy
  end

  def welcome
    self.name
  end

  def self.beginning_of_day
    #utc_hour = Time.now.utc.hour
    #time_zone_hour_stamp = - utc_hour
    #time_zone_hour_stamp = utc_hour if utc_hour > 11
    #time_zone = ActiveSupport::TimeZone[time_zone_hour_stamp]
    #time_zone = time_zone.to_s.gsub(/\(.*\) /,"")
    #puts "Update Points for #{time_zone}"
    teens = Teen.all.map{|t| t if t.time.hour == 0}.compact.flatten
    teens.each{|t| t.count_points}
    #self.where(:time_zone => time_zone).each{|t| t.count_points}
  end

  def self.image_style
    { :medium => "300x300>", :thumb => "100x100>", :index => "30x30>", :welcome => "118x134#" }
  end

  def count_points
    puts "#{self.name} #{self.points}"
    update_attribute(:points, [50, points + 50].min)
    puts "#{self.name} #{self.points}"
    reports = incident_reports.where{(created_at >= my{(time - 1.day).beginning_of_day}) & (created_at <= my{time.beginning_of_day})}
    new_points = reports.inject(points){|sum, r| sum -= r.points_loss}
    puts "#{new_points}"
    update_attribute(:points, [50, new_points].min)
    puts "#{self.name} #{self.points}"
  end

  private

  def set_up_time_zone
    self.time_zone ||= self.family.time_zone
  end

  def copy_default_guidelines
    self.guidelines << DefaultGuideline.all.map{|g| g.copy}
  end

  def copy_default_daily_privileges
    self.daily_privileges << DefaultDailyPrivilege.all.map{|g| g.copy}
  end

end

app/controllers/family/daily_privileges_controller.rb
class Family::DailyPrivilegesController < InheritedResources::Base

  before_filter :set_instance_values
  before_filter :check_user
  respond_to :js, :only => [:create, :update, :destroy ]

  def create
    if @daily_privilege.update_attributes(params[:daily_privilege])
      render :layout => "application.js"
    else
      flash[:alert] = "Fill all fields!"
      render :layout => "application.js"
    end
  end

  def index
    @daily_privileges = @teen.daily_privileges.order(:position)
  end

  def update
    update!{ {:layout => "application.js"} }
  end

  def destroy
    destroy! { {:layout => "application.js"} }
  end

  def sort
    @daily_privileges = @teen.daily_privileges
    @daily_privileges.each do |daily_privilege|
      daily_privilege.position = params['daily_privilege'].index(daily_privilege.id.to_s) + 1
      daily_privilege.save!
    end
    render :nothing => true
  end

  private

  def set_instance_values
    @teen = current_user.teens.find(params[:teen_id]) if params[:teen_id]
    params[:id] ? @daily_privilege = @teen.daily_privileges.find(params[:id]) : @daily_privilege = DailyPrivilege.new
  end

end

app/controllers/family/guidelines_controller.rb
class Family::GuidelinesController < InheritedResources::Base

  before_filter :set_instance_values
  before_filter :check_user

  def index
    @guidelines = @teen.guidelines
  end

  def edit
  end

  def update
    update! do |success, failure|
      success.html {redirect_to [:family, @teen, :guidelines], notice: "Guideline was successfully updated." }
      success.js { render :layout => "application.js" }
    end
  end

  def create
    if @guideline.update_attributes(params[:guideline])
      render :layout => "application.js"
    else
      flash[:alert] = "Fill all fields!"
      render :layout => "application.js"
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html{redirect_to families_teen_guidelines_path(@teen), notice: "Guideline was successfully destroyed."}
      success.js{ render :layout => "application.js"}
    end
  end

  private

  def set_instance_values
    if current_user.is_a?(Family)
      @teen = current_user.teens.find(params[:teen_id]) if params[:teen_id]
      params[:id] ? @guideline = @teen.guidelines.find(params[:id]) : @guideline = Guideline.new
    else
      @guideline = current_user.guidelines.find(params[:id])
    end
  end

end

app/controllers/family/incident_reports_controller.rb
class Family::IncidentReportsController < InheritedResources::Base

  before_filter :set_variables
  before_filter :check_user

  def history
    @incident_reports = @teen.incident_reports
  end

  def review_self_correct
  end

  def review_appeal
  end

  def create
    @incident_report = IncidentReport.new(params[:incident_report])
    if @incident_report.save
      redirect_to [:history, :family, @teen, :incident_reports], notice: 'Incident Report was successfully created.'
    else
      redirect_to [:history, :family, @teen, :incident_reports], alert: "Fill all fields!"
    end
  end

  def update
    update! do |success, failure|
      success.html {redirect_to request.referer, notice: "#{params[:commit]} was successfully sended!" }
    end
  end

  private

  def set_variables
    @teen = Teen.find(params[:teen_id])
    @incident_report =  params[:id] ? IncidentReport.find(params[:id]) : IncidentReport.new
  end
end

app/controllers/family/subscription_plans_controller.rb
class Family::SubscriptionPlansController < ApplicationController

  before_filter :check_user

  def index
  end

end

app/controllers/family/teens_controller.rb
class Family::TeensController < InheritedResources::Base

  before_filter :set_teen
  before_filter :check_user

  def create
    @teen = Teen.new(params[:teen])
    if @teen.save
      redirect_to family_teens_path, notice: 'Teen was successfully created.'
    else
      render action: "edit"
    end
  end

  def index
    @teens = current_user.teens
  end

  def update
    respond_to do |format|
      if @teen.update_attributes(params[:teen])
        format.html { redirect_to request.referer, notice: 'Teen was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def settings
  end

  def daily_priveleges_sort
    @daily_privileges = current_user.daily_privileges << DailyPrivilege.default
    @daily_privileges.each do |daily_privilege|
      daily_privilege.position = params['daily_privilege'].index(daily_privilege.id.to_s) + 1
      daily_privilege.save!
    end
  end

  private

  def set_teen
    params[:id] ? @teen = current_user.teens.find(params[:id]) : @teen = Teen.new
  end

end

app/controllers/teen/daily_privileges_controller.rb
class Teen::DailyPrivilegesController < InheritedResources::Base

  def index
    @available_points = current_user.points.to_i
    points_enough = @available_points/10
    points_enough = 0 if points_enough < 0
    @daily_privileges = current_user.daily_privileges.active.order(:position).first(points_enough)
  end

end

app/controllers/teen/guidelines_controller.rb
class Teen::GuidelinesController < InheritedResources::Base

  def index
    @guidelines = current_user.guidelines.active
  end

end

app/controllers/teen/incident_reports_controller.rb
class Teen::IncidentReportsController < InheritedResources::Base

  def self_correct
    @incident_report =  IncidentReport.find(params[:id])
  end

  def appeal
    @incident_report =  IncidentReport.find(params[:id])
  end

  protected

  def collection
    @incident_reports ||= current_user.incident_reports
  end

end

app/helpers/teens/daily_privileges_helper.rb
module Teens::DailyPrivilegesHelper
end

app/helpers/teens/guidelines_helper.rb
module Teens::GuidelinesHelper
end

app/helpers/teens/incident_reports_helper.rb
module Teens::IncidentReportsHelper
end

app/views/family/teens/_form.html.haml
= form_for([:family, @teen], :html => { :multipart => true }, :validate => :bottom_js) do |f|
  - if @teen.errors.any?
    #error_explanation
      %h2
        = pluralize(@teen.errors.to_a.uniq.count, "error")
        prohibited this teen from being saved:
      %ul
        - @teen.errors.full_messages.uniq.each do |msg|
          %li= msg
  .input-control.text.span7
    = f.text_field :name, :autofocus => true, :class => 'with-helper', :placeholder => 'Name'
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.text.span7
    = f.text_field :email, :class => 'with-helper', :placeholder => 'Email', :validate => {:uniqueness => true, :presence => true}
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.text.span7
    = f.text_field :phone, :class => 'with-helper', :placeholder => 'Phone'
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.text.span7
    = f.text_field :date_of_birth, :class => 'with-helper datepicker_field', :placeholder => 'Date Of Birth(MM/DD/YYYY)'
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.password.span7
    = f.password_field :password, :class => 'with-helper', :placeholder => 'Password', :validate => {:confirmation => true}
  .input-control.password.span7
    = f.password_field :password_confirmation, :class => 'with-helper', :placeholder => 'Confirm password'
    %button.helper{:type => 'button', :tabindex => "-1"}
  .input-control.password.span7
    = f.label "Photo"
    = f.file_field :avatar

  = f.hidden_field :family_id, :value => current_user.id
  .actions
    - if params[:action] == "edit"
      = f.submit "Update Teen"
    - if params[:action] == "index"
      = f.submit "Add Teen"
      %a.button{:onclick => "$.Dialog.hide()", :form => "#"} Cancel

app/views/family/teens/_teen_list_item.html.haml
= link_to edit_family_teen_path(teen) do
  %li.bg-color-red.fg-color-white
    .icon
      - if teen.avatar.present?
        %img{:src => teen.avatar.url(:index)}/
      - else
        %img{:src => '/avatars/index/missing.png'}/
    .data
      %h4.fg-color-white= teen.name
      %p

app/views/family/teens/edit.html.haml
%h2 Editing teen
= render 'form'

app/views/family/teens/index.html.haml
%h2 Teens
%ul.listview.iconic.teens
  - @teens.each do |teen|
    = render "teen_list_item", teen: teen
%ul.listview.iconic
  %li#add_teen
    .icon
      %i.icon-plus-2{:style => "font-size: 20px; margin:4px 2px;"}
    .data
      %h4 Add Teen
:javascript
  $(document).ready(function(){
      $('#add_teen').click(function(e) {
          $.Dialog({
              'title'      : 'Add Teen',
              'content'    : "#{j render(:partial => 'form')}",
              'position'   : {
                'offsetY'    : 50
              },
              'buttons'    : {

              }
          });
        $("#new_teen").validate();
      });

  });

app/views/family/teens/settings.html.haml
%h2 Settings #{@teen.name}
%br
.tile.bg-color-blueDark
  = link_to edit_family_teen_path(@teen) do
    .tile.bg-color-red.icon
      .tile-content
        %i.icon-user
      .brand
        .name Personal Settings

.tile.bg-color-yellow
  = link_to family_teen_guidelines_path(@teen) do
    .tile.bg-color-yellow.icon
      .tile-content
        %i.icon-clipboard-2
      .brand
        .name Guidelines
.tile.bg-color-green
  = link_to family_teen_daily_privileges_path(@teen) do
    .tile.bg-color-green.icon
      .tile-content
        %i.icon-star-3
      .brand
        .name Daily Privileges
.tile.bg-color-red
  = link_to family_teen_incident_reports_path(@teen) do
    .tile.bg-color-red.icon
      .tile-content
        %i.icon-lightning-2
      .brand
        .name Incident Reports